first_django_project/api/urls.py
from django.urls import path, include
from api.models import CategoryResource, CourseResource
from tastypie.api import Api

# examplyary of how to use the API resources in the urls.py file

api = Api(api_name='v1')
course_resource = CourseResource()
category_resource = CategoryResource()
api.register(course_resource)
api.register(category_resource)

urlpatterns = [
    path('', include(api.urls), name='index'),
]

first_django_project/base/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('api/', include('api.urls')),
]

first_django_project/shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>', views.single_course, name='single_course')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

first_django_project/api/models.py
from tastypie.resources import ModelResource
from .authentication import CustomAuthentication
from tastypie.authorization import Authorization
from shop.models import Category, Course


class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allow_methods = ['get']


class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allow_methods = ['get', 'post', 'put', 'delete']
        excludes = ['created_at', 'reviews_qty']
        authentication = CustomAuthentication()
        authorization = Authorization()

    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return super().hydrate(bundle)

    def dehydrate(self, bundle):
        bundle.data['category_id'] = bundle.obj.category_id
        bundle.data['category'] = bundle.obj.category
        return super().dehydrate(bundle)

    def dehydrate_title(self, bundle):
        return bundle.data['title'].upper()

first_django_project/shop/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=300)
    price = models.FloatField()
    students_qty = models.IntegerField()
    images = models.ImageField("Images", blank=True, null=True)
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

first_django_project/api/views.py
from django.shortcuts import render

first_django_project/shop/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Course


def index(request):
    courses = Course.objects.all()
    return render(request, 'shop/courses.html', {'courses': courses})


def single_course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/single_course.html', {'course': course})

first_django_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <a href="{% url 'shop:index' %}" class="navbar-brand">Courses Shop</a>
        <span class="navbar-text">
          <a href="/admin/" class="me-2" target="_blank">Admin</a>
          <a href="/api/v1/" target="_blank">Api</a>
        </span>
      </div>
      
    </nav>
    <main class="container">{% block content %} {% endblock content %}</main>
  </body>
</html>

first_django_project/templates/shop/courses.html
{% extends 'base.html' %} {% block title %} All courses {%endblock %} 

{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Courses</title>
  </head>

  <body>
    <table class="table mt-5 table-bordered table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th>Title</th>
          <th>Category</th>
          <th>Price</th>
          <th>Students Quantity</th>
          <th>Images</th>
          <th>Buy option</th>
        </tr>
      </thead>
      <tbody>
        {% for course in courses %}
        <tr>
          <td><a href={{course.id}}>{{course.title}}</a></td>
          <td>{{course.category}}</td>
          <td>{{course.price}}</td>
          <td>{{course.students_qty}}</td>
          <td>
            <div class="container">
              {% if course.images %}
            <img src="{{ course.images.url }}" alt="{{ course.name }}" width="100" height="80">
            {% else %}
            No image
            {% endif %}
            </div>
          </td>
          <td><button class="btn btn-primary">Buy</button></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>
{% endblock content %}

first_django_project/templates/shop/single_course.html
{% extends 'base.html'%}

{% block title %} {{course.title}} {%endblock %} 


{% block content %}
    <h1 class="mt-5">{{course.title}}</h1>
    <h2>{{course.category}}</h2>
    <p>Price: {{course.price}}</p>
    <p>Stundents Quantity:{{course.students_qty}}</p>
    <button class="btn btn-primary">Buy</button>
{% endblock  %}